[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name              tail
    Path              /logs/GatewayService.log
    Tag               gateway
    Read_from_Head    true
    Skip_Long_Lines   On

[INPUT]
    Name              tail
    Path              /logs/OrderService.log
    Tag               order
    Read_from_Head    true
    Skip_Long_Lines   On

[INPUT]
    Name              tail
    Path              /logs/PaymentService.log
    Tag               payment
    Read_from_Head    true
    Skip_Long_Lines   On

[INPUT]
    Name              tail
    Path              /logs/BankService.log
    Tag               bank
    Read_from_Head    true
    Skip_Long_Lines   On

[OUTPUT]
    Name        loki
    Match       gateway
    Host        loki
    Port        3100
    Labels      job=devopsstudy,service=GatewayService
    Line_Format key_value

[OUTPUT]
    Name        loki
    Match       order
    Host        loki
    Port        3100
    Labels      job=devopsstudy,service=OrderService
    Line_Format key_value

[OUTPUT]
    Name        loki
    Match       payment
    Host        loki
    Port        3100
    Labels      job=devopsstudy,service=PaymentService
    Line_Format key_value

[OUTPUT]
    Name        loki
    Match       bank
    Host        loki
    Port        3100
    Labels      job=devopsstudy,service=BankService
    Line_Format key_value
