input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if ![service_name] {
    mutate {
      add_field => {
        "service_name" => "unknown-service"
      }
    }
  }

  if ![event_dataset] {
    mutate {
      add_field => {
        "event_dataset" => "application.logs"
      }
    }
  }

  mutate {
    copy => {
      "service_name" => "service_index"
    }
  }

  mutate {
    lowercase => ["service_index"]
  }
}

output {
  if [event_dataset] == "demo.metrics" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "devopsstudy-metrics-%{service_index}-%{+yyyy.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "devopsstudy-logs-%{service_index}-%{+yyyy.MM.dd}"
    }
  }

  stdout {
    codec => rubydebug
  }
}
