server:
  port: 8081

spring:
  main:
    banner-mode: "off"
  application:
    name: OrderService

logging:
  level:
    root: WARN
    com.observe.order: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,shutdown
  endpoint:
    shutdown:
      access: unrestricted
  tracing:
    sampling:
      probability: 1.0

services:
  payment:
    url: http://localhost:8082
