server:
  port: 8081

spring:
  main:
    banner-mode: "off"
  application:
    name: OrderService

logging:
  level:
    root: WARN
    com.observe.order: INFO

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      otlp:
        enabled: true
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
          transport: http
        
services:
  payment:
    url: http://localhost:8082
