server:
  port: 8083

spring:
  main:
    banner-mode: "off"
  application:
    name: BankService

logging:
  level:
    root: WARN
    com.observe.bank: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  metrics:
    tags:
      application: ${spring.application.name}
  otlp:
    metrics:
      export:
        enabled: true
        url: http://localhost:4318/v1/metrics
        step: 5s
  tracing:
    sampling:
      probability: 1.0
