server:
  port: 8083

spring:
  main:
    banner-mode: "off"
  application:
    name: BankService

logging:
  level:
    root: WARN
    com.observe.bank: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,shutdown
  endpoint:
    shutdown:
      access: unrestricted
  tracing:
    sampling:
      probability: 1.0
