server:
  port: 8080

spring:
  main:
    banner-mode: "off"
  application:
    name: GatewayService
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service
              uri: http://localhost:8081
              predicates:
                - Path=/orders/**

logging:
  level:
    root: WARN
    com.observe.gateway: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,shutdown
  endpoint:
    shutdown:
      access: unrestricted
  tracing:
    sampling:
      probability: 1.0
